service: default
runtime: nodejs20

handlers:
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  login: admin
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  login: admin
